version: "3"

networks:
  gitea:
    driver: bridge
##################################
##################################
#################################

services:

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - /home/gitea/mysql:/var/lib/mysql

###################################
##################################
##################################
  server:
    image: gitea/gitea:main-nightly
    container_name: gitea
    environment:
      - USER_UID=1001
      - USER_GID=1001
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - /home/gitea/data:/data
      - /home/gitea/timezone:/etc/timezone:ro
      - /home/gitea/localtime:/etc/localtime:ro
    ports:
     - "5050:3000"
     - "222:22"
    depends_on:
     - db